// export const host = "http://localhost:3042";
// export const baseURL = "";
// global.baseURL = "";
// global.host = "http://localhost:3042";
// global.host = "http://192.168.56.101:3042";
global.competitionDuration = 0;
global.competitionStart = 0;
global.baseURL = "/dmc";
global.host = "http://acm.ut.ac.ir/dmc";